### ISSUE TITLE
Sketch uses 6514 bytes (108%) of program storage space. Maximum is 6012 bytes. (Digispark)

### ISSUE THREAD

**Issue by rradar** [moononournation/ATtinyPowerMeter#1]
Hello @moononournation 
sorry to bother. I stumbled upon your instructables yesterday and were very impressed by your work. I anted to start right away with this project. I don't have attiny85 but a digispark which is driven by a tiny85.

I have the first one in this picture:
![image](https://user-images.githubusercontent.com/34582688/49581756-45982200-f953-11e8-9fe6-0750f9a1258f.png)

I tried to compile your sketch with the arduino IDE 1.8.6 but get the following error message:

```
Sketch uses 6514 bytes (108%) of program storage space. Maximum is 6012 bytes.
Global variables use 110 bytes of dynamic memory.

Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board Digispark (Default - 16.5mhz).
```

Is there anything I can do about it? I would really like to have this DIY Power Meter :cry: 

![image](https://user-images.githubusercontent.com/34582688/49582043-0f0ed700-f954-11e8-8e4d-baba63bc01f3.png)

**Comment by rradar** [comment]
I think I found the important diffrence between a pure ATTiny85 and the digispark.

- The ATTiny85 has supposed to have a storage of **8KB**.
- The Digispark also has supposed to have a storage of **8KB**. **BUT**: it is just able to utilize **6KB** (because of the bootloader)

So the question:
Is it possible to shrink the code by 8% (=502 bytes) to fit into the digispark? Maybe a lite version... even though I have no idea were to save space :confused:

**Comment by moononournation** [comment]
Hi radar, there are INA219 and SSD1306 exist before I made this project. I cannot use those library because it cannot fit in 8 KB storage. My tailor-made libraries already squeeze much in size. I think there are still 2 places you may try:

- Font.h, it contains characters from ASCII code 32 to 126, you may trim some not used in this project.

- Rewrite all floating point variables to integer, according to Arduino web site, it can save 2KB in size: http://www.arduino.cc/en/Guide/Troubleshooting#size

**Comment by rradar** [comment]
Hi @moononournation 

thank's for your feedback! Meanwhile I had success to shrink my boot loader (see this [instructable](https://www.instructables.com/id/Refresh-Your-DigiSpark-clone-With-a-Smaller-Bootlo/) for more) of the digispark to have unbelievable usable space for program code of **6714** bytes! :smiley:

Right now I have only problems to flash *any* program code via arduino on my digispark. But I will get over it hopefully! https://github.com/micronucleus/micronucleus/issues/130 previously and now https://github.com/micronucleus/micronucleus/issues/131

**Comment by moononournation** [comment]
It is a good news to heard that the reset pin still work to flash latest micronucleus!

**Comment by rradar** [comment]
It works @moononournation !

![image](https://user-images.githubusercontent.com/34582688/49687245-be88ac80-fb00-11e8-9f54-efac29424cb5.png)

Thank's a lot! I made it :smiley:

**Comment by moononournation** [comment]
As per your screen output, you may still using the outdated TinyWireM library bundle with DigiSpark. You can download the bug fixed version at Arduino Library Manager.

**Comment by rradar** [comment]
@moononournation thank's for your feedback! How can you see it? Is it the spots on the right side in the screen? My screen actually has one dead line you can see in the mWh...

Does it just help to download the TinyWireM library in arduino and than compile the sketch again? Or is it necessary to do more steps like changing the code?

**Comment by moononournation** [comment]
yes, download, compile and upload
