### ISSUE TITLE
BRNG bit is not set in high_value_mode

### ISSUE THREAD

**Issue by zalexua** [moononournation/ATtinyPowerMeter#3]
BRNG bit is not set when you switch to to_high_value_mode()
#define CONFIG_UPPER_3A 0b00011100
should be 
#define CONFIG_UPPER_3A 0b00111100
while it's checked when reading read_bus_voltage()

**Comment by moononournation** [comment]
Oh yes, seems I have been missing the Bus Voltage Range. Have you tried the readings is correct after the changes?

**Comment by zalexua** [comment]
> Oh yes, seems I have been missing the Bus Voltage Range. Have you tried the readings is correct after the changes?

Yes. That just allows more wide range of voltages.
Here is nice reading about that.
https://e2e.ti.com/support/amplifiers-group/amplifiers/f/amplifiers-forum/686865/ina219-bus-voltage-accuracy
According to it full voltage ()32v range is just better than 16v, so by default it would be better.
